name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
           mkdir /home/runner/work/publish/
           sed "s/\:.*/:$(shell git describe --tags)/" clashg/version
           cat clashg/version
           ls -lah
           cd ..
           tar -zcf clashg.tar.gz --exclude=clashg/.git --exclude=clashg/.github clashg
           pwd
           ls -lah
           echo ~
           ls -lah ~/work/clashg/clashg.tar.gz
           mv ~/work/clashg/clashg.tar.gz /home/runner/work/publish/

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() && startsWith(github.ref, 'refs/tags/')}}
        with:
          tag: ${{ github.ref }}
          files: /home/runner/work/publish/*
          generate_release_notes: true
