name: 构建

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
           ls -lah
           rm -rf .git
           cd ..
           tar zcf clashg.tar.gz clashg
           pwd
           ls -lah
           echo "${{GITHUB_ACTION_PATH}}"
      - name: upload github actions
        uses: actions/upload-artifact@v3
        with:
          name: clashg.tar.gz
          path: clashg.tar.gz
          if-no-files-found: error
