name: 构建

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
           ls -lah
           cd ..
           tar -zcf clashg.tar.gz --exclude=clashg/.git --exclude=clashg/.github clashg
           pwd
           ls -lah
           echo "${GITHUB_ACTION_PATH}"
           echo ~
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag: alpha
          files: ~/work/clashg/clashg.tar.gz
          generate_release_notes: true           
